{"name": "test_login_1_failed_error_data[data0]", "status": "passed", "attachments": [{"name": "log", "source": "d318f30f-de2e-4998-9db3-1dbf531e61ff-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720559', 'passwd': 'python', 'check': '此账号没有经过授权，请联系管理员!'}"}], "start": 1608217369253, "stop": 1608217370076, "uuid": "46185a49-5fc3-4d76-87ed-0435a514a616", "historyId": "6a46fcdafac322ca966e3107b2e7a7bd", "testCaseId": "1fc2970947168ce03ea67fcd12d25389", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_1_failed_error_data", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "56724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}