{"name": "test_login_1_failed_error_data[data1]", "status": "passed", "attachments": [{"name": "log", "source": "57cac9c6-682d-47b0-bb48-d24a88e6ecc2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': 'python11', 'check': '帐号或密码错误!'}"}], "start": 1608217606472, "stop": 1608217607182, "uuid": "6336db5e-f0d3-4726-a052-020af9fe8137", "historyId": "308aaeb32698655c72872f8225ec1a01", "testCaseId": "1fc2970947168ce03ea67fcd12d25389", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_1_failed_error_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "7508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}