{"name": "test_login_1_failed_error_data[data0]", "status": "passed", "attachments": [{"name": "log", "source": "099250b7-e0a1-40fa-a6ce-e7aee21e9475-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "1d72bbab-c629-4cfd-84ef-ff54c44dfa26-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720559', 'passwd': 'python', 'check': '此账号没有经过授权，请联系管理员!'}"}], "start": 1608132624949, "stop": 1608132625724, "uuid": "db34f159-62a9-4224-9285-38b929d52ef4", "historyId": "6a46fcdafac322ca966e3107b2e7a7bd", "testCaseId": "1fc2970947168ce03ea67fcd12d25389", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_1_failed_error_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "53180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}