{"name": "test_login_1_failed_error_data[data1]", "status": "passed", "attachments": [{"name": "log", "source": "1e4e48fe-610a-4fe7-84ca-411a8c525049-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "data", "value": "{'user': '18684720553', 'passwd': 'python11', 'check': '帐号或密码错误!'}"}], "start": 1608299395716, "stop": 1608299396402, "uuid": "c330c53f-0e0c-4e7f-9106-b24646f9c3dd", "historyId": "308aaeb32698655c72872f8225ec1a01", "testCaseId": "1fc2970947168ce03ea67fcd12d25389", "fullName": "testcase.test_1login_pytest.TestLogin#test_login_1_failed_error_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('refresh_page')"}, {"name": "tag", "value": "login"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_1login_pytest"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-J6CF24D"}, {"name": "thread", "value": "59000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_1login_pytest"}]}